name: zkevm-contracts-images

on: workflow_dispatch

jobs:
  buildx:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        fork:
          - id: 4
            branch: v1.1.0-fork.4
          - id: 5
            branch: v2.0.0-fork.5
          - id: 6
            branch: v3.0.0-fork.6
          - id: 7
            branch: v4.0.0-fork.7
          - id: 8
            branch: v5.0.1-rc.2-fork.8
          - id: 9
            branch: develop

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: leovct
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          tags: leovct/zkevm-contracts:fork${{ matrix.fork.id }}
          build-args: |
            ZKEVM_CONTRACTS_BRANCH=${{ matrix.fork.branch }}
            POLYCLI_VERSION=main
          platforms: linux/amd64,linux/arm64
          push: true
